version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
