#!/usr/bin/env python3
from gevent import monkey

monkey.patch_all()

import pitop.common.ptdm  # noqa: E402
import zmq.green  # noqa: E402

# Use zmq.green for gevent compatibility
pitop.common.ptdm.zmq = zmq.green

import logging  # noqa: E402
from os import geteuid  # noqa: E402
from signal import SIGINT, SIGTERM  # noqa: E402
from sys import exit  # noqa: E402

import click  # noqa: E402
import click_logging  # noqa: E402
from gevent import signal_handler, wait  # noqa: E402

from pt_os_web_portal.app import App  # noqa: E402

logger = logging.getLogger()
click_logging.basic_config(logger)

logging.getLogger("pitop").setLevel(logging.INFO)


def is_root() -> bool:
    return geteuid() == 0


def configure_interrupt_signals(app):
    def handler(*_):
        logger.info("Stopping...")
        app.stop()
        logger.debug("Stopped!")
        exit(0)

    signal_handler(SIGINT, handler)
    signal_handler(SIGTERM, handler)


@click.command()
@click.option(
    "-t",
    "--test-mode",
    help="test mode",
    is_flag=True,
)
@click_logging.simple_verbosity_option(logger)
@click.version_option()
def main(test_mode):
    if not is_root():
        print("pi-topOS Web Portal must be run as root!")
        exit(1)

    app = App(test_mode)
    configure_interrupt_signals(app)
    app.start()
    wait()


if __name__ == "__main__":
    main(prog_name="pt-os-web-portal")  # pragma: no cover
