debian/extra/pt-os-about.svg                          /usr/share/icons/hicolor/scalable/apps
debian/extra/pt-os-about.desktop                      /usr/share/applications
debian/extra/pt-os-updater.desktop                    /usr/share/applications
debian/extra/pt-os-setup.desktop                      /usr/lib/pt-os-web-portal/applications
debian/extra/pt-os-tour.desktop                       /usr/lib/pt-os-web-portal/applications
debian/extra/pwdptwp.sh                               /usr/lib/pt-os-web-portal/notify
debian/extra/notify-on-port-busy.sh                   /usr/lib/pt-os-web-portal/notify
