debian/extra/pwdptwp.sh                     /usr/lib/pt-os-web-portal
src/notify-on-port-busy.sh                  /usr/lib/pt-os-web-portal
src/server/Pipfile*                         /usr/lib/pt-os-web-portal
src/server/__main__.py                      /usr/lib/pt-os-web-portal
src/server/backend                          /usr/lib/pt-os-web-portal
src/miniscreen                              /usr/lib/pt-os-web-portal
resources                                   /usr/lib/pt-os-web-portal
