debian/extras/notify-on-port-busy.sh        /usr/lib/pt-web-portal
debian/extras/pwdptwp.sh                    /usr/lib/pt-web-portal
src/expand-fs.sh                            /usr/lib/pt-web-portal
src/miniscreen                              /usr/lib/pt-web-portal
src/server/backend                          /usr/lib/pt-web-portal
src/server/run.py                           /usr/lib/pt-web-portal
