name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Run tests and generate coverage report
        run: |
          cd src/server
          pipenv install --dev
          PYTHONPATH=backend pipenv run pytest --verbose --cov-report term-missing --cov=backend
          pipenv run coverage xml

      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./src/server/coverage.xml
          flags: unittests
          env_vars: OS,PYTHON,JAVASCRIPT
          fail_ci_if_error: true
          verbose: true
