name: Test and Build Packages on All Commits
# TODO: provide latest commit to 'master' as pre-release GitHub Release

# Don't run on branches intended for CI modifications
on:
  push:
    branches-ignore:
      - "ci-test-*"

jobs:
  test-python-linting:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Lint code
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "src/server"
          use-flake8: true
          extra-flake8-options: "--max-line-length=150 --exclude=src/server/tests/*"

          use-pylint: false
          # extra-pylint-options: ""

          use-pycodestyle: false
          # extra-pycodestyle-options: ""

          use-black: false
          # extra-black-options: ""

          use-mypy: false
          # extra-mypy-options: ""

          use-isort: false
          # extra-isort-options: ""

  run-unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker run \
            --rm \
            --name onboarding-py-tests \
            --volume ${{ github.workspace }}:/src \
            --env RUN_PYTHON_TESTS=1 \
            --env PYTHON_TESTS_DIR=src/server/tests \
            --env PYTHON_TARGET_DIR=src/server \
            --env PYTHON_COVERAGE_DIR=backend \
            --env RUN_WEB_TESTS=1 \
            --env WEB_TESTS_DIR=src/frontend/onboarding \
            pitop/test-run

  build-debian-packages:
    needs: [ test-python-linting, run-unit-tests ]
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Patch changelog (snapshot)
        run: |
          docker run --rm \
            --volume ${{ github.workspace }}:/src \
            -e RELEASE=0 \
            pitop/gbp-dch-gen:latest

      - name: Add 'debian-changelog-line-too-long' Lintian override for patched changelog
        run: |
          grep "^Package: " debian/control | awk '{print $2}' | xargs -n1 -I % sh -c "echo '%: debian-changelog-line-too-long' >> debian/%.lintian-overrides"

      - name: Build Debian package
        run: |
          mkdir -p /tmp/artifacts/{src,bin}
          docker run --rm \
            --volume ${{ github.workspace }}:/src \
            --volume /tmp/artifacts/bin:/build \
            pitop/deb-build:latest

      - name: Separate Debian source package files from binary
        run: |
          mv /tmp/artifacts/bin/* /tmp/artifacts/src/
          mv /tmp/artifacts/src/*.deb /tmp/artifacts/bin/

      - name: Upload Debian source package files
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-deb-src"
          path: "/tmp/artifacts/src/"

      - name: Upload Debian binary packages
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-deb"
          path: "/tmp/artifacts/bin/"
