name: Create Changelog Update Pull Request

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  create-version-update-changelog-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Patch changelog (release)
        run: |
          docker run --rm \
            --volume ${{ github.workspace }}:/src \
            -e RELEASE=1 \
            pitop/gbp-dch-gen:latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "ci_version_bump"
          commit-message: "Update changelog: v${{ env.VERSION }}"
          title: "Update Debian package changelog for next release"
          body: "Modify the changelog as necessary (e.g. amend version, tidy format), then squash and merge (leave commit message unchanged).
Use `release.yml` to create GitHub Release and any additional package management (e.g. upload to public release repositories)."
          draft: false
          labels: "ci"
